services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    extends:
      file: shared/common.yml
      service: app
    volumes:
      - "${CONFIG_DIR}/ddclient:/config"
    restart: unless-stopped
