services:
  # dockerproxy:
  #   image: ghcr.io/tecnativa/docker-socket-proxy:latest
  #   container_name: dockerproxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped
  #   environment:
  #     - CONTAINERS=1
  #     - POST=0

  letsencrypt:
    image: linuxserver/swag:latest
    container_name: letsencrypt
    extends:
      file: shared/common.yml
      service: app
    cap_add:
      - NET_ADMIN
    volumes:
      - "${CONFIG_DIR}/letsencrypt:/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - plex
      - overseerr
      - radarr
      - sonarr
      - prowlarr
      - nextcloud
    environment:
      - EMAIL=$EMAIL
      - URL=$DOMAIN
      - SUBDOMAINS=$SUBDOMAINS
      - DNSPLUGIN=gandi
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      # - DOCKER_HOST=dockerproxy
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-cloudflare-real-ip
    ports:
      - 80:80
      - 81:81
      - 443:443
