services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    hostname: nextcloud
    container_name: nextcloud
    extends:
      file: shared/common.yml
      service: app
    network_mode: bridge
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - "${CONFIG_DIR}/nextcloud:/config"
      - "${DATA_DIR}/nextcloud:/data"
    ports:
      - 444:443
