services:
  plex:
    image: linuxserver/plex:latest
    hostname: plex
    container_name: plex
    extends:
      file: shared/common.yml
      service: app
    volumes:
      - "${CONFIG_DIR}/plex:/config"
    devices:
      - /dev/dri:/dev/dri
