services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /tmp/gluetun/:/tmp/gluetun/
    ports:
      - 8888:8888/tcp # http proxy
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - SERVER_COUNTRIES=$OPENVPN_COUNTRY
      - VPN_PORT_FORWARDING=on
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_STEALTH=on
      - HTTPPROXY_USER=$USERNAME
      - HTTPPROXY_PASSWORD=$PASSWORD
    labels:
      - swag=enable
      - swag_port=9091
