services:
  sonarr:
    image: linuxserver/sonarr:latest
    hostname: sonarr
    container_name: sonarr
    extends:
      file: shared/common.yml
      service: app
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
