services:
  syncthing:
    image: linuxserver/syncthing:latest
    hostname: syncthing
    container_name: syncthing
    extends:
      file: shared/common.yml
      service: app
    volumes:
      - "${CONFIG_DIR}/syncthing/:/config"
