services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    extends:
      file: shared/common.yml
      service: app
    volumes:
      # cache on the ssd
      - /home/nuc/cache:/cache
      - "${CONFIG_DIR}/transmission:/config"
    environment:
      - USER=$USERNAME
      - PASS=$PASSWORD
      - DOCKER_MODS=linuxserver/mods:transmission-transmissionic
    labels:
      - swag=enable
      - swag_address=proxy
    network_mode: "service:proxy"
